// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this file,
// You can obtain one at http://mozilla.org/MPL/2.0/.
//
// Copyright (c) 2026, Lukas Scheller lukasscheller@icloud.com
use crate::latin_1::Latin1Str;
#[allow(clippy::upper_case_acronyms)]
#[derive(PartialEq, Eq, Copy, Clone, Debug)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub enum TokenKind {
    #[doc = "A keyword, such as `entity`, `architecture` or `abs`."]
    Keyword(Keyword),
    #[doc = "`+`"]
    Plus,
    #[doc = "`-`"]
    Minus,
    #[doc = "`=`"]
    EQ,
    #[doc = "`/=`"]
    NE,
    #[doc = "`<`"]
    LT,
    #[doc = "`<=`"]
    LTE,
    #[doc = "`>`"]
    GT,
    #[doc = "`>=`"]
    GTE,
    #[doc = "`?=`"]
    QueEQ,
    #[doc = "`?/=`"]
    QueNE,
    #[doc = "`?<`"]
    QueLT,
    #[doc = "`?<=`"]
    QueLTE,
    #[doc = "`?>`"]
    QueGT,
    #[doc = "`?>=`"]
    QueGTE,
    #[doc = "`?`"]
    Que,
    #[doc = "`??`"]
    QueQue,
    #[doc = "`*`"]
    Times,
    #[doc = "`**`"]
    Pow,
    #[doc = "`/`"]
    Div,
    #[doc = "`'`"]
    Tick,
    #[doc = "`(`"]
    LeftPar,
    #[doc = "`)`"]
    RightPar,
    #[doc = "`[`"]
    LeftSquare,
    #[doc = "`]`"]
    RightSquare,
    #[doc = "`;`"]
    SemiColon,
    #[doc = "`:`"]
    Colon,
    #[doc = "`|`"]
    Bar,
    #[doc = "`.`"]
    Dot,
    #[doc = "`<>`"]
    BOX,
    #[doc = "`<<`"]
    LtLt,
    #[doc = "`>>`"]
    GtGt,
    #[doc = "`^`"]
    Circ,
    #[doc = "`@`"]
    CommAt,
    #[doc = "`&`"]
    Concat,
    #[doc = "`,`"]
    Comma,
    #[doc = "`:=`"]
    ColonEq,
    #[doc = "`=>`"]
    RightArrow,
    Identifier,
    AbstractLiteral,
    StringLiteral,
    BitStringLiteral,
    CharacterLiteral,
    ToolDirective,
    #[doc = "Unknown input\n\nProduced, for example, when there is an unknown char or illegal bit string"]
    Unknown,
    #[doc = "Special End of File token.\nHas no source representation but may carry trivia"]
    Eof,
}
impl TokenKind {
    #[doc = r" Every token kind, with `Keyword` expanded to one entry per keyword"]
    pub const ALL: [TokenKind; 161] = [
        Self::Keyword(Keyword::Abs),
        Self::Keyword(Keyword::Access),
        Self::Keyword(Keyword::After),
        Self::Keyword(Keyword::Alias),
        Self::Keyword(Keyword::All),
        Self::Keyword(Keyword::And),
        Self::Keyword(Keyword::Architecture),
        Self::Keyword(Keyword::Array),
        Self::Keyword(Keyword::Assert),
        Self::Keyword(Keyword::Assume),
        Self::Keyword(Keyword::Attribute),
        Self::Keyword(Keyword::Begin),
        Self::Keyword(Keyword::Block),
        Self::Keyword(Keyword::Body),
        Self::Keyword(Keyword::Buffer),
        Self::Keyword(Keyword::Bus),
        Self::Keyword(Keyword::Case),
        Self::Keyword(Keyword::Component),
        Self::Keyword(Keyword::Configuration),
        Self::Keyword(Keyword::Constant),
        Self::Keyword(Keyword::Context),
        Self::Keyword(Keyword::Cover),
        Self::Keyword(Keyword::Default),
        Self::Keyword(Keyword::Disconnect),
        Self::Keyword(Keyword::Downto),
        Self::Keyword(Keyword::Else),
        Self::Keyword(Keyword::Elsif),
        Self::Keyword(Keyword::End),
        Self::Keyword(Keyword::Entity),
        Self::Keyword(Keyword::Exit),
        Self::Keyword(Keyword::Fairness),
        Self::Keyword(Keyword::File),
        Self::Keyword(Keyword::For),
        Self::Keyword(Keyword::Force),
        Self::Keyword(Keyword::Function),
        Self::Keyword(Keyword::Generate),
        Self::Keyword(Keyword::Generic),
        Self::Keyword(Keyword::Group),
        Self::Keyword(Keyword::Guarded),
        Self::Keyword(Keyword::If),
        Self::Keyword(Keyword::Impure),
        Self::Keyword(Keyword::In),
        Self::Keyword(Keyword::Inertial),
        Self::Keyword(Keyword::Inout),
        Self::Keyword(Keyword::Is),
        Self::Keyword(Keyword::Label),
        Self::Keyword(Keyword::Library),
        Self::Keyword(Keyword::Linkage),
        Self::Keyword(Keyword::Literal),
        Self::Keyword(Keyword::Loop),
        Self::Keyword(Keyword::Map),
        Self::Keyword(Keyword::Mod),
        Self::Keyword(Keyword::Nand),
        Self::Keyword(Keyword::New),
        Self::Keyword(Keyword::Next),
        Self::Keyword(Keyword::Nor),
        Self::Keyword(Keyword::Not),
        Self::Keyword(Keyword::Null),
        Self::Keyword(Keyword::Of),
        Self::Keyword(Keyword::On),
        Self::Keyword(Keyword::Open),
        Self::Keyword(Keyword::Or),
        Self::Keyword(Keyword::Others),
        Self::Keyword(Keyword::Out),
        Self::Keyword(Keyword::Package),
        Self::Keyword(Keyword::Parameter),
        Self::Keyword(Keyword::Port),
        Self::Keyword(Keyword::Postponed),
        Self::Keyword(Keyword::Procedure),
        Self::Keyword(Keyword::Process),
        Self::Keyword(Keyword::Property),
        Self::Keyword(Keyword::Protected),
        Self::Keyword(Keyword::Private),
        Self::Keyword(Keyword::Pure),
        Self::Keyword(Keyword::Range),
        Self::Keyword(Keyword::Record),
        Self::Keyword(Keyword::Register),
        Self::Keyword(Keyword::Reject),
        Self::Keyword(Keyword::Release),
        Self::Keyword(Keyword::Rem),
        Self::Keyword(Keyword::Report),
        Self::Keyword(Keyword::Restrict),
        Self::Keyword(Keyword::Return),
        Self::Keyword(Keyword::Rol),
        Self::Keyword(Keyword::Ror),
        Self::Keyword(Keyword::Select),
        Self::Keyword(Keyword::Sequence),
        Self::Keyword(Keyword::Severity),
        Self::Keyword(Keyword::Signal),
        Self::Keyword(Keyword::Shared),
        Self::Keyword(Keyword::Sla),
        Self::Keyword(Keyword::Sll),
        Self::Keyword(Keyword::Sra),
        Self::Keyword(Keyword::Srl),
        Self::Keyword(Keyword::Strong),
        Self::Keyword(Keyword::Subtype),
        Self::Keyword(Keyword::Then),
        Self::Keyword(Keyword::To),
        Self::Keyword(Keyword::Transport),
        Self::Keyword(Keyword::Type),
        Self::Keyword(Keyword::Unaffected),
        Self::Keyword(Keyword::Units),
        Self::Keyword(Keyword::Until),
        Self::Keyword(Keyword::Use),
        Self::Keyword(Keyword::Variable),
        Self::Keyword(Keyword::View),
        Self::Keyword(Keyword::Vpgk),
        Self::Keyword(Keyword::Vmode),
        Self::Keyword(Keyword::Vprop),
        Self::Keyword(Keyword::Vunit),
        Self::Keyword(Keyword::Wait),
        Self::Keyword(Keyword::When),
        Self::Keyword(Keyword::While),
        Self::Keyword(Keyword::With),
        Self::Keyword(Keyword::Xnor),
        Self::Keyword(Keyword::Xor),
        Self::Plus,
        Self::Minus,
        Self::EQ,
        Self::NE,
        Self::LT,
        Self::LTE,
        Self::GT,
        Self::GTE,
        Self::QueEQ,
        Self::QueNE,
        Self::QueLT,
        Self::QueLTE,
        Self::QueGT,
        Self::QueGTE,
        Self::Que,
        Self::QueQue,
        Self::Times,
        Self::Pow,
        Self::Div,
        Self::Tick,
        Self::LeftPar,
        Self::RightPar,
        Self::LeftSquare,
        Self::RightSquare,
        Self::SemiColon,
        Self::Colon,
        Self::Bar,
        Self::Dot,
        Self::BOX,
        Self::LtLt,
        Self::GtGt,
        Self::Circ,
        Self::CommAt,
        Self::Concat,
        Self::Comma,
        Self::ColonEq,
        Self::RightArrow,
        Self::Identifier,
        Self::AbstractLiteral,
        Self::StringLiteral,
        Self::BitStringLiteral,
        Self::CharacterLiteral,
        Self::ToolDirective,
        Self::Unknown,
        Self::Eof,
    ];
    #[doc = r" Returns the canonical text representation of this token kind, or `None` if the token"]
    #[doc = r" kind has no fixed text (e.g. identifiers or literals)."]
    pub fn canonical_text(&self) -> Option<&'static Latin1Str> {
        match self {
            Self::Keyword(kw) => Some(kw.canonical_text()),
            Self::Plus => Some(Latin1Str::new(b"+")),
            Self::Minus => Some(Latin1Str::new(b"-")),
            Self::EQ => Some(Latin1Str::new(b"=")),
            Self::NE => Some(Latin1Str::new(b"/=")),
            Self::LT => Some(Latin1Str::new(b"<")),
            Self::LTE => Some(Latin1Str::new(b"<=")),
            Self::GT => Some(Latin1Str::new(b">")),
            Self::GTE => Some(Latin1Str::new(b">=")),
            Self::QueEQ => Some(Latin1Str::new(b"?=")),
            Self::QueNE => Some(Latin1Str::new(b"?/=")),
            Self::QueLT => Some(Latin1Str::new(b"?<")),
            Self::QueLTE => Some(Latin1Str::new(b"?<=")),
            Self::QueGT => Some(Latin1Str::new(b"?>")),
            Self::QueGTE => Some(Latin1Str::new(b"?>=")),
            Self::Que => Some(Latin1Str::new(b"?")),
            Self::QueQue => Some(Latin1Str::new(b"??")),
            Self::Times => Some(Latin1Str::new(b"*")),
            Self::Pow => Some(Latin1Str::new(b"**")),
            Self::Div => Some(Latin1Str::new(b"/")),
            Self::Tick => Some(Latin1Str::new(b"'")),
            Self::LeftPar => Some(Latin1Str::new(b"(")),
            Self::RightPar => Some(Latin1Str::new(b")")),
            Self::LeftSquare => Some(Latin1Str::new(b"[")),
            Self::RightSquare => Some(Latin1Str::new(b"]")),
            Self::SemiColon => Some(Latin1Str::new(b";")),
            Self::Colon => Some(Latin1Str::new(b":")),
            Self::Bar => Some(Latin1Str::new(b"|")),
            Self::Dot => Some(Latin1Str::new(b".")),
            Self::BOX => Some(Latin1Str::new(b"<>")),
            Self::LtLt => Some(Latin1Str::new(b"<<")),
            Self::GtGt => Some(Latin1Str::new(b">>")),
            Self::Circ => Some(Latin1Str::new(b"^")),
            Self::CommAt => Some(Latin1Str::new(b"@")),
            Self::Concat => Some(Latin1Str::new(b"&")),
            Self::Comma => Some(Latin1Str::new(b",")),
            Self::ColonEq => Some(Latin1Str::new(b":=")),
            Self::RightArrow => Some(Latin1Str::new(b"=>")),
            Self::Eof => Some(Latin1Str::new(b"")),
            Self::Identifier
            | Self::AbstractLiteral
            | Self::StringLiteral
            | Self::BitStringLiteral
            | Self::CharacterLiteral
            | Self::ToolDirective
            | Self::Unknown => None,
        }
    }
}
#[doc = r" All available keywords in the latest (VHDL 2019) edition of VHDL"]
#[derive(PartialEq, Eq, Clone, Copy, Debug)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub enum Keyword {
    Abs,
    Access,
    After,
    Alias,
    All,
    And,
    Architecture,
    Array,
    Assert,
    Assume,
    Attribute,
    Begin,
    Block,
    Body,
    Buffer,
    Bus,
    Case,
    Component,
    Configuration,
    Constant,
    Context,
    Cover,
    Default,
    Disconnect,
    Downto,
    Else,
    Elsif,
    End,
    Entity,
    Exit,
    Fairness,
    File,
    For,
    Force,
    Function,
    Generate,
    Generic,
    Group,
    Guarded,
    If,
    Impure,
    In,
    Inertial,
    Inout,
    Is,
    Label,
    Library,
    Linkage,
    Literal,
    Loop,
    Map,
    Mod,
    Nand,
    New,
    Next,
    Nor,
    Not,
    Null,
    Of,
    On,
    Open,
    Or,
    Others,
    Out,
    Package,
    Parameter,
    Port,
    Postponed,
    Procedure,
    Process,
    Property,
    Protected,
    Private,
    Pure,
    Range,
    Record,
    Register,
    Reject,
    Release,
    Rem,
    Report,
    Restrict,
    Return,
    Rol,
    Ror,
    Select,
    Sequence,
    Severity,
    Signal,
    Shared,
    Sla,
    Sll,
    Sra,
    Srl,
    Strong,
    Subtype,
    Then,
    To,
    Transport,
    Type,
    Unaffected,
    Units,
    Until,
    Use,
    Variable,
    View,
    Vpgk,
    Vmode,
    Vprop,
    Vunit,
    Wait,
    When,
    While,
    With,
    Xnor,
    Xor,
}
impl Keyword {
    #[doc = r" Every keyword, in alphabetical order"]
    pub const ALL: [Keyword; 116] = [
        Self::Abs,
        Self::Access,
        Self::After,
        Self::Alias,
        Self::All,
        Self::And,
        Self::Architecture,
        Self::Array,
        Self::Assert,
        Self::Assume,
        Self::Attribute,
        Self::Begin,
        Self::Block,
        Self::Body,
        Self::Buffer,
        Self::Bus,
        Self::Case,
        Self::Component,
        Self::Configuration,
        Self::Constant,
        Self::Context,
        Self::Cover,
        Self::Default,
        Self::Disconnect,
        Self::Downto,
        Self::Else,
        Self::Elsif,
        Self::End,
        Self::Entity,
        Self::Exit,
        Self::Fairness,
        Self::File,
        Self::For,
        Self::Force,
        Self::Function,
        Self::Generate,
        Self::Generic,
        Self::Group,
        Self::Guarded,
        Self::If,
        Self::Impure,
        Self::In,
        Self::Inertial,
        Self::Inout,
        Self::Is,
        Self::Label,
        Self::Library,
        Self::Linkage,
        Self::Literal,
        Self::Loop,
        Self::Map,
        Self::Mod,
        Self::Nand,
        Self::New,
        Self::Next,
        Self::Nor,
        Self::Not,
        Self::Null,
        Self::Of,
        Self::On,
        Self::Open,
        Self::Or,
        Self::Others,
        Self::Out,
        Self::Package,
        Self::Parameter,
        Self::Port,
        Self::Postponed,
        Self::Procedure,
        Self::Process,
        Self::Property,
        Self::Protected,
        Self::Private,
        Self::Pure,
        Self::Range,
        Self::Record,
        Self::Register,
        Self::Reject,
        Self::Release,
        Self::Rem,
        Self::Report,
        Self::Restrict,
        Self::Return,
        Self::Rol,
        Self::Ror,
        Self::Select,
        Self::Sequence,
        Self::Severity,
        Self::Signal,
        Self::Shared,
        Self::Sla,
        Self::Sll,
        Self::Sra,
        Self::Srl,
        Self::Strong,
        Self::Subtype,
        Self::Then,
        Self::To,
        Self::Transport,
        Self::Type,
        Self::Unaffected,
        Self::Units,
        Self::Until,
        Self::Use,
        Self::Variable,
        Self::View,
        Self::Vpgk,
        Self::Vmode,
        Self::Vprop,
        Self::Vunit,
        Self::Wait,
        Self::When,
        Self::While,
        Self::With,
        Self::Xnor,
        Self::Xor,
    ];
    #[doc = r" Returns the canonical (lowercase) text for this keyword."]
    pub fn canonical_text(&self) -> &'static Latin1Str {
        match self {
            Self::Abs => Latin1Str::new(b"abs"),
            Self::Access => Latin1Str::new(b"access"),
            Self::After => Latin1Str::new(b"after"),
            Self::Alias => Latin1Str::new(b"alias"),
            Self::All => Latin1Str::new(b"all"),
            Self::And => Latin1Str::new(b"and"),
            Self::Architecture => Latin1Str::new(b"architecture"),
            Self::Array => Latin1Str::new(b"array"),
            Self::Assert => Latin1Str::new(b"assert"),
            Self::Assume => Latin1Str::new(b"assume"),
            Self::Attribute => Latin1Str::new(b"attribute"),
            Self::Begin => Latin1Str::new(b"begin"),
            Self::Block => Latin1Str::new(b"block"),
            Self::Body => Latin1Str::new(b"body"),
            Self::Buffer => Latin1Str::new(b"buffer"),
            Self::Bus => Latin1Str::new(b"bus"),
            Self::Case => Latin1Str::new(b"case"),
            Self::Component => Latin1Str::new(b"component"),
            Self::Configuration => Latin1Str::new(b"configuration"),
            Self::Constant => Latin1Str::new(b"constant"),
            Self::Context => Latin1Str::new(b"context"),
            Self::Cover => Latin1Str::new(b"cover"),
            Self::Default => Latin1Str::new(b"default"),
            Self::Disconnect => Latin1Str::new(b"disconnect"),
            Self::Downto => Latin1Str::new(b"downto"),
            Self::Else => Latin1Str::new(b"else"),
            Self::Elsif => Latin1Str::new(b"elsif"),
            Self::End => Latin1Str::new(b"end"),
            Self::Entity => Latin1Str::new(b"entity"),
            Self::Exit => Latin1Str::new(b"exit"),
            Self::Fairness => Latin1Str::new(b"fairness"),
            Self::File => Latin1Str::new(b"file"),
            Self::For => Latin1Str::new(b"for"),
            Self::Force => Latin1Str::new(b"force"),
            Self::Function => Latin1Str::new(b"function"),
            Self::Generate => Latin1Str::new(b"generate"),
            Self::Generic => Latin1Str::new(b"generic"),
            Self::Group => Latin1Str::new(b"group"),
            Self::Guarded => Latin1Str::new(b"guarded"),
            Self::If => Latin1Str::new(b"if"),
            Self::Impure => Latin1Str::new(b"impure"),
            Self::In => Latin1Str::new(b"in"),
            Self::Inertial => Latin1Str::new(b"inertial"),
            Self::Inout => Latin1Str::new(b"inout"),
            Self::Is => Latin1Str::new(b"is"),
            Self::Label => Latin1Str::new(b"label"),
            Self::Library => Latin1Str::new(b"library"),
            Self::Linkage => Latin1Str::new(b"linkage"),
            Self::Literal => Latin1Str::new(b"literal"),
            Self::Loop => Latin1Str::new(b"loop"),
            Self::Map => Latin1Str::new(b"map"),
            Self::Mod => Latin1Str::new(b"mod"),
            Self::Nand => Latin1Str::new(b"nand"),
            Self::New => Latin1Str::new(b"new"),
            Self::Next => Latin1Str::new(b"next"),
            Self::Nor => Latin1Str::new(b"nor"),
            Self::Not => Latin1Str::new(b"not"),
            Self::Null => Latin1Str::new(b"null"),
            Self::Of => Latin1Str::new(b"of"),
            Self::On => Latin1Str::new(b"on"),
            Self::Open => Latin1Str::new(b"open"),
            Self::Or => Latin1Str::new(b"or"),
            Self::Others => Latin1Str::new(b"others"),
            Self::Out => Latin1Str::new(b"out"),
            Self::Package => Latin1Str::new(b"package"),
            Self::Parameter => Latin1Str::new(b"parameter"),
            Self::Port => Latin1Str::new(b"port"),
            Self::Postponed => Latin1Str::new(b"postponed"),
            Self::Procedure => Latin1Str::new(b"procedure"),
            Self::Process => Latin1Str::new(b"process"),
            Self::Property => Latin1Str::new(b"property"),
            Self::Protected => Latin1Str::new(b"protected"),
            Self::Private => Latin1Str::new(b"private"),
            Self::Pure => Latin1Str::new(b"pure"),
            Self::Range => Latin1Str::new(b"range"),
            Self::Record => Latin1Str::new(b"record"),
            Self::Register => Latin1Str::new(b"register"),
            Self::Reject => Latin1Str::new(b"reject"),
            Self::Release => Latin1Str::new(b"release"),
            Self::Rem => Latin1Str::new(b"rem"),
            Self::Report => Latin1Str::new(b"report"),
            Self::Restrict => Latin1Str::new(b"restrict"),
            Self::Return => Latin1Str::new(b"return"),
            Self::Rol => Latin1Str::new(b"rol"),
            Self::Ror => Latin1Str::new(b"ror"),
            Self::Select => Latin1Str::new(b"select"),
            Self::Sequence => Latin1Str::new(b"sequence"),
            Self::Severity => Latin1Str::new(b"severity"),
            Self::Signal => Latin1Str::new(b"signal"),
            Self::Shared => Latin1Str::new(b"shared"),
            Self::Sla => Latin1Str::new(b"sla"),
            Self::Sll => Latin1Str::new(b"sll"),
            Self::Sra => Latin1Str::new(b"sra"),
            Self::Srl => Latin1Str::new(b"srl"),
            Self::Strong => Latin1Str::new(b"strong"),
            Self::Subtype => Latin1Str::new(b"subtype"),
            Self::Then => Latin1Str::new(b"then"),
            Self::To => Latin1Str::new(b"to"),
            Self::Transport => Latin1Str::new(b"transport"),
            Self::Type => Latin1Str::new(b"type"),
            Self::Unaffected => Latin1Str::new(b"unaffected"),
            Self::Units => Latin1Str::new(b"units"),
            Self::Until => Latin1Str::new(b"until"),
            Self::Use => Latin1Str::new(b"use"),
            Self::Variable => Latin1Str::new(b"variable"),
            Self::View => Latin1Str::new(b"view"),
            Self::Vpgk => Latin1Str::new(b"vpgk"),
            Self::Vmode => Latin1Str::new(b"vmode"),
            Self::Vprop => Latin1Str::new(b"vprop"),
            Self::Vunit => Latin1Str::new(b"vunit"),
            Self::Wait => Latin1Str::new(b"wait"),
            Self::When => Latin1Str::new(b"when"),
            Self::While => Latin1Str::new(b"while"),
            Self::With => Latin1Str::new(b"with"),
            Self::Xnor => Latin1Str::new(b"xnor"),
            Self::Xor => Latin1Str::new(b"xor"),
        }
    }
    #[doc = r" Returns the keyword corresponding to the given Latin-1 string, or `None` if the string"]
    #[doc = r" is not a keyword. The comparison is case-insensitive."]
    pub fn from_latin1(s: &Latin1Str) -> Option<Self> {
        keyword_map!(
            s.as_bytes(),
            [
                (b"abs", Abs),
                (b"access", Access),
                (b"after", After),
                (b"alias", Alias),
                (b"all", All),
                (b"and", And),
                (b"architecture", Architecture),
                (b"array", Array),
                (b"assert", Assert),
                (b"assume", Assume),
                (b"attribute", Attribute),
                (b"begin", Begin),
                (b"block", Block),
                (b"body", Body),
                (b"buffer", Buffer),
                (b"bus", Bus),
                (b"case", Case),
                (b"component", Component),
                (b"configuration", Configuration),
                (b"constant", Constant),
                (b"context", Context),
                (b"cover", Cover),
                (b"default", Default),
                (b"disconnect", Disconnect),
                (b"downto", Downto),
                (b"else", Else),
                (b"elsif", Elsif),
                (b"end", End),
                (b"entity", Entity),
                (b"exit", Exit),
                (b"fairness", Fairness),
                (b"file", File),
                (b"for", For),
                (b"force", Force),
                (b"function", Function),
                (b"generate", Generate),
                (b"generic", Generic),
                (b"group", Group),
                (b"guarded", Guarded),
                (b"if", If),
                (b"impure", Impure),
                (b"in", In),
                (b"inertial", Inertial),
                (b"inout", Inout),
                (b"is", Is),
                (b"label", Label),
                (b"library", Library),
                (b"linkage", Linkage),
                (b"literal", Literal),
                (b"loop", Loop),
                (b"map", Map),
                (b"mod", Mod),
                (b"nand", Nand),
                (b"new", New),
                (b"next", Next),
                (b"nor", Nor),
                (b"not", Not),
                (b"null", Null),
                (b"of", Of),
                (b"on", On),
                (b"open", Open),
                (b"or", Or),
                (b"others", Others),
                (b"out", Out),
                (b"package", Package),
                (b"parameter", Parameter),
                (b"port", Port),
                (b"postponed", Postponed),
                (b"procedure", Procedure),
                (b"process", Process),
                (b"property", Property),
                (b"protected", Protected),
                (b"private", Private),
                (b"pure", Pure),
                (b"range", Range),
                (b"record", Record),
                (b"register", Register),
                (b"reject", Reject),
                (b"release", Release),
                (b"rem", Rem),
                (b"report", Report),
                (b"restrict", Restrict),
                (b"return", Return),
                (b"rol", Rol),
                (b"ror", Ror),
                (b"select", Select),
                (b"sequence", Sequence),
                (b"severity", Severity),
                (b"signal", Signal),
                (b"shared", Shared),
                (b"sla", Sla),
                (b"sll", Sll),
                (b"sra", Sra),
                (b"srl", Srl),
                (b"strong", Strong),
                (b"subtype", Subtype),
                (b"then", Then),
                (b"to", To),
                (b"transport", Transport),
                (b"type", Type),
                (b"unaffected", Unaffected),
                (b"units", Units),
                (b"until", Until),
                (b"use", Use),
                (b"variable", Variable),
                (b"view", View),
                (b"vpgk", Vpgk),
                (b"vmode", Vmode),
                (b"vprop", Vprop),
                (b"vunit", Vunit),
                (b"wait", Wait),
                (b"when", When),
                (b"while", While),
                (b"with", With),
                (b"xnor", Xnor),
                (b"xor", Xor),
            ]
        )
        .copied()
    }
}
