// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this file,
// You can obtain one at http://mozilla.org/MPL/2.0/.
//
// Copyright (c)  2024, Lukas Scheller lukasscheller@icloud.com

use crate::standard::VHDLStandard;

// `TokenKind`, `Keyword` and their text conversions are generated by `cargo xtask codegen`
// from `xtask/src/model/token.rs`.
pub use super::generated::{Keyword, TokenKind};

impl TokenKind {
    /// Checks whether this token is the special EoF (End of File) token.
    // Note: This is commonly used in the parser and therefore defined here.
    pub fn is_eof(&self) -> bool {
        self == &TokenKind::Eof
    }
}

impl Keyword {
    /// Returns the VHDL standard that first reserved this keyword.
    pub fn introduced_in(self) -> VHDLStandard {
        use VHDLStandard::*;
        match self {
            // VHDL 2019
            Self::View | Self::Private | Self::Vpgk => VHDL2019,
            // VHDL 2008
            // Also introduces keywords "assume_guarantee" and "restrict_guarantee".
            // However as they only appear in this specific standard and are revoked later,
            // they are treated as identifiers unless there is a feature request to support this.
            Self::Assume
            | Self::Context
            | Self::Cover
            | Self::Default
            | Self::Fairness
            | Self::Force
            | Self::Parameter
            | Self::Property
            | Self::Release
            | Self::Restrict
            | Self::Sequence
            | Self::Strong
            | Self::Vmode
            | Self::Vprop
            | Self::Vunit => VHDL2008,
            // VHDL 2000
            // Also introduces keywords "Procedural" and "Reference"
            // Similar cases as for VHDL2000 (the keywords are only valid in 2008 and thus omitted).
            Self::Protected => VHDL2000,
            // VHDL 1993
            Self::Group
            | Self::Impure
            | Self::Inertial
            | Self::Literal
            | Self::Postponed
            | Self::Pure
            | Self::Reject
            | Self::Rol
            | Self::Ror
            | Self::Shared
            | Self::Sla
            | Self::Sll
            | Self::Sra
            | Self::Srl
            | Self::Unaffected
            | Self::Xnor => VHDL1993,
            // Everything else: VHDL 1987
            _ => VHDL1987,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::latin_1::Latin1String;

    #[test]
    fn keyword_text_round_trips() {
        for kw in Keyword::ALL {
            let text = kw.canonical_text();
            assert_eq!(Keyword::from_latin1(text), Some(kw));
            assert_eq!(Keyword::from_latin1(&text.to_uppercase()), Some(kw));
        }
    }

    #[test]
    fn all_token_kinds_are_distinct() {
        for (i, kind) in TokenKind::ALL.iter().enumerate() {
            assert!(!TokenKind::ALL[..i].contains(kind), "{kind:?} listed twice");
        }
        let texts: Vec<Latin1String> = TokenKind::ALL
            .iter()
            .filter_map(|kind| kind.canonical_text())
            .map(|text| text.to_owned())
            .collect();
        for (i, text) in texts.iter().enumerate() {
            assert!(
                !texts[..i].contains(text),
                "{text} is the text of two kinds"
            );
        }
    }
}
