[package]
name = "vhdl_syntax"
version = "0.1.0"
authors = ["Lukas Scheller"]
readme = "README.md"
description = "VHDL parser for lossless concrete syntax trees"
categories = ["parser-implementations", "development-tools"]
keywords = ["vhdl", "parser", "cst", "syntax-tree"]
documentation = "https://docs.rs/vhdl_syntax"
homepage = "https://github.com/VHDL-LS/rust_hdl/tree/master/vhdl_syntax"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
nonzero_ext = "0.3.0"
rustc-hash = "2.1.3"
serde = { version = "1.0.228", optional = true, features = ["derive"]}

[dev-dependencies]
assert_matches = "1.5.0"
pretty_assertions = "1.4.1"
insta = { version = "1.36", features = ["redactions"] }
similar = { version = "3.1.2", features = ["bytes"] }

[features]
serde = ["dep:serde"]
default = []

[package.metadata.docs.rs]
all-features = true
