//! Renders the rule pages of the vhdl-lint book from the rules' documentation.
//!
//! Everything below `rules/` is generated, as is the part of `SUMMARY.md` between
//! [`SUMMARY_START`] and [`SUMMARY_END`]; the rest of the book is written by hand.
//! The entries are indented like the start marker, so indenting both markers below
//! a list item nests the rule pages under it.

use std::ops::Range;

use pulldown_cmark::{Event, HeadingLevel, Parser, Tag};
use vhdl_lint::rule::{ErasedAstRule, RuleRegistry};

pub const RULES_DIR: &str = "rules";

pub const SUMMARY_START: &str = "<!-- rules: generated by `cargo xtask lint-docs` -->";
pub const SUMMARY_END: &str = "<!-- end of rules -->";

const GENERATED_HEADER: &str = "<!-- Generated by `cargo xtask lint-docs`. Do not edit. -->";

/// A generated page: its path relative to the book's `src`, and its contents.
pub struct Page {
    pub path: String,
    pub contents: String,
}

/// Every rule in `registry`, ordered by code.
fn sorted_rules(registry: &RuleRegistry) -> Vec<&dyn ErasedAstRule> {
    let mut rules = registry.rules().collect::<Vec<_>>();
    rules.sort_by_key(|rule| (rule.code().category(), rule.code().number()));
    rules
}

fn page_path(rule: &dyn ErasedAstRule) -> String {
    format!("{RULES_DIR}/{}.md", rule.docs().name)
}

fn yes_no(value: bool) -> &'static str {
    if value {
        "yes"
    } else {
        "no"
    }
}

/// Every page below [`RULES_DIR`]: the index, and one page for each rule.
pub fn pages(registry: &RuleRegistry) -> Vec<Page> {
    let rules = sorted_rules(registry);
    let mut pages = vec![Page {
        path: format!("{RULES_DIR}/README.md"),
        contents: index(&rules),
    }];
    pages.extend(rules.iter().map(|&rule| Page {
        path: page_path(rule),
        contents: rule_page(rule),
    }));
    pages
}

fn index(rules: &[&dyn ErasedAstRule]) -> String {
    let mut out = format!(
        "{GENERATED_HEADER}\n\n\
         # Rules\n\n\
         | Code | Name | Summary | Enabled by default |\n\
         | --- | --- | --- | --- |\n"
    );
    for rule in rules {
        let docs = rule.docs();
        out.push_str(&format!(
            "| `{}` | [{}]({}.md) | {} | {} |\n",
            rule.code(),
            docs.name,
            docs.name,
            docs.summary.replace('|', "\\|"),
            yes_no(rule.is_enabled_by_default()),
        ));
    }
    out
}

fn rule_page(rule: &dyn ErasedAstRule) -> String {
    let docs = rule.docs();
    let code = rule.code();
    let (state, action, key, flag) = if rule.is_enabled_by_default() {
        ("enabled", "disable", "ignore", "--ignore")
    } else {
        ("disabled", "enable", "select", "--select")
    };
    format!(
        "{GENERATED_HEADER}\n\n\
         # {name} ({code})\n\n\
         | Category | Severity | Enabled by default |\n\
         | --- | --- | --- |\n\
         | {category:?} | {severity} | {enabled} |\n\n\
         {text}\n\n\
         ## Configuration\n\n\
         This rule is {state} by default. To {action} it, add it to `{key}` in `vhdl-lint.toml`:\n\n\
         ```toml\n\
         {key} = [\"{code}\"]\n\
         ```\n\n\
         or pass `{flag} {code}` on the command line.\n",
        name = docs.name,
        category = code.category(),
        severity = rule.severity(),
        enabled = yes_no(rule.is_enabled_by_default()),
        text = shift_headings(docs.text),
    )
}

/// Moves every heading in `markdown` one level down, so that a rule's
/// documentation nests below the page's title. A heading at the lowest level
/// stays there.
fn shift_headings(markdown: &str) -> String {
    let mut edits = Vec::<(Range<usize>, String)>::new();
    for (event, range) in Parser::new(markdown).into_offset_iter() {
        let Event::Start(Tag::Heading { level, .. }) = event else {
            continue;
        };
        if level == HeadingLevel::H6 {
            continue;
        }
        let source = &markdown[range.clone()];
        match source.find('#') {
            // An ATX heading (`# Title`) whose opening sequence starts at `start`
            Some(start) if source[..start].trim().is_empty() => {
                let at = range.start + start;
                edits.push((at..at, "#".to_owned()));
            }
            // A setext heading (`Title` underlined with `=` or `-`) becomes an ATX heading
            _ => {
                let mut lines = source.trim_end().lines().collect::<Vec<_>>();
                lines.pop();
                let title = lines.iter().map(|line| line.trim()).collect::<Vec<_>>();
                let hashes = "#".repeat(level as usize + 1);
                let end = range.start + source.trim_end().len();
                edits.push((range.start..end, format!("{hashes} {}", title.join(" "))));
            }
        }
    }

    let mut out = String::with_capacity(markdown.len() + edits.len());
    let mut copied = 0;
    for (range, replacement) in edits {
        out.push_str(&markdown[copied..range.start]);
        out.push_str(&replacement);
        copied = range.end;
    }
    out.push_str(&markdown[copied..]);
    out
}

/// The lines of `SUMMARY.md` that list the rule pages, each starting with `indent`.
fn summary_entries(registry: &RuleRegistry, indent: &str) -> String {
    sorted_rules(registry)
        .iter()
        .map(|&rule| format!("{indent}- [{}]({})\n", rule.docs().name, page_path(rule)))
        .collect()
}

/// `summary` with the part between [`SUMMARY_START`] and [`SUMMARY_END`] replaced
/// by the list of rule pages.
pub fn update_summary(summary: &str, registry: &RuleRegistry) -> anyhow::Result<String> {
    let (Some(start), Some(end)) = (summary.find(SUMMARY_START), summary.find(SUMMARY_END)) else {
        anyhow::bail!("SUMMARY.md must contain the lines `{SUMMARY_START}` and `{SUMMARY_END}`");
    };
    anyhow::ensure!(
        start < end,
        "`{SUMMARY_START}` must come before `{SUMMARY_END}` in SUMMARY.md"
    );
    let line_start = |at: usize| summary[..at].rfind('\n').map_or(0, |i| i + 1);
    let indent = &summary[line_start(start)..start];
    // The entries replace every line between the markers' lines
    let after_start = summary[start..]
        .find('\n')
        .map_or(summary.len(), |i| start + i + 1);
    let before_end = line_start(end);
    anyhow::ensure!(
        after_start <= before_end,
        "`{SUMMARY_START}` and `{SUMMARY_END}` must be on separate lines of SUMMARY.md"
    );
    Ok(format!(
        "{}{}{}",
        &summary[..after_start],
        summary_entries(registry, indent),
        &summary[before_end..]
    ))
}

#[cfg(test)]
mod tests {
    use super::*;
    use vhdl_lint::rule::register_builtin_rules;

    fn builtin() -> RuleRegistry {
        let mut registry = RuleRegistry::new();
        register_builtin_rules(&mut registry);
        registry
    }

    #[test]
    fn headings_move_one_level_down() {
        assert_eq!(
            shift_headings("Text\n\n# One\n\n## Two\n\n###### Six\n"),
            "Text\n\n## One\n\n### Two\n\n###### Six\n"
        );
    }

    #[test]
    fn setext_headings_become_atx_headings() {
        assert_eq!(
            shift_headings("Title\n=====\n\nSub\n---\n\nText"),
            "## Title\n\n### Sub\n\nText"
        );
    }

    #[test]
    fn a_hash_in_a_code_block_is_not_a_heading() {
        let markdown = "```text\n# not a heading\n```\n";
        assert_eq!(shift_headings(markdown), markdown);
    }

    #[test]
    fn every_rule_gets_a_page_and_an_index_entry() {
        let registry = builtin();
        let pages = pages(&registry);
        let index = &pages[0];
        assert_eq!(index.path, "rules/README.md");
        for rule in registry.rules() {
            let name = rule.docs().name;
            let path = format!("rules/{name}.md");
            assert!(pages.iter().any(|page| page.path == path), "{path}");
            assert!(index.contents.contains(&format!("[{name}]({name}.md)")));
        }
    }

    #[test]
    fn a_rule_page_shows_how_to_toggle_the_rule() {
        let pages = pages(&builtin());
        let page = |name: &str| {
            &pages
                .iter()
                .find(|page| page.path == format!("rules/{name}.md"))
                .unwrap()
                .contents
        };

        let disabled = page("no-parens-around-if");
        assert!(disabled.contains("# no-parens-around-if (IDM001)\n"));
        assert!(disabled.contains("\n## Non-compliant example\n"));
        assert!(disabled.contains("select = [\"IDM001\"]"));
        assert!(disabled.contains("`--select IDM001`"));

        let enabled = page("explicit-port-mode");
        assert!(enabled.contains("ignore = [\"IDM002\"]"));
    }

    #[test]
    fn the_summary_lists_the_rules_between_the_markers() {
        let summary = format!(
            "# Summary\n\n- [Rules](rules/README.md)\n  {SUMMARY_START}\n  - [stale](rules/stale.md)\n  {SUMMARY_END}\n- [After](after.md)\n"
        );
        assert_eq!(
            update_summary(&summary, &builtin()).unwrap(),
            format!(
                "# Summary\n\n- [Rules](rules/README.md)\n  {SUMMARY_START}\n  \
                 - [no-parens-around-if](rules/no-parens-around-if.md)\n  \
                 - [explicit-port-mode](rules/explicit-port-mode.md)\n  \
                 {SUMMARY_END}\n- [After](after.md)\n"
            )
        );
    }

    #[test]
    fn a_summary_without_markers_is_rejected() {
        assert!(update_summary("# Summary\n", &builtin()).is_err());
    }
}
