pub mod doc;
pub mod explicit_port_mode;
pub mod no_parens_around_if;
pub mod registry;
pub mod selection;

pub use doc::Documented;
pub use registry::{RegisterError, RuleRegistry};

use vhdl_syntax::{
    parser::error::Span,
    standard::VHDLStandard,
    syntax::{validate::valid_node::Valid, AstNode, NodeKind, SyntaxNode},
};

use crate::{
    diagnostic::Diagnostic,
    error_code::ErrorCode,
    fix::{edit::Edits, Fix},
    rule::{
        doc::RuleDocs, explicit_port_mode::ExplicitPortMode, no_parens_around_if::NoParensAroundIf,
    },
    severity::Severity,
    source_loc::SourceLoc,
    FileId, FileSettings,
};

/// Holds context for checking a rule
pub struct AstRuleCtx<'a> {
    diagnostics: &'a mut Vec<Diagnostic>,
    // The severity for this error
    severity: Severity,
    // The file that this rule applies to
    // Note that AstRules only refer to their own file, therefore this lives in the context.
    file: FileId,
    // The error-code of this rule
    code: ErrorCode,
    // settings from the file belonging to this context
    settings: FileSettings,
}

pub struct DiagnosticBuilder<'a>(&'a mut Diagnostic);

impl<'a> DiagnosticBuilder<'a> {
    pub fn with_fix(self, fix: Fix) -> DiagnosticBuilder<'a> {
        self.0.set_fix(fix);
        self
    }

    pub fn with_note(self, note: impl Into<String>) -> DiagnosticBuilder<'a> {
        self.0.set_note(note);
        self
    }
}

impl<'a> AstRuleCtx<'a> {
    pub(crate) fn new(
        diagnostics: &mut Vec<Diagnostic>,
        severity: Severity,
        file: FileId,
        code: ErrorCode,
        settings: FileSettings,
    ) -> AstRuleCtx<'_> {
        AstRuleCtx {
            diagnostics,
            severity,
            file,
            code,
            settings,
        }
    }

    pub fn push(&mut self, span: Span, message: impl Into<String>) -> DiagnosticBuilder<'_> {
        self.diagnostics.push(Diagnostic::new(
            message,
            self.severity,
            SourceLoc::new(self.file, span),
            self.code,
        ));
        DiagnosticBuilder(self.diagnostics.last_mut().unwrap())
    }

    pub fn standard(&self) -> VHDLStandard {
        self.settings.standard
    }

    pub fn edits(&self) -> Edits {
        Edits::new(self.standard())
    }
}

/// A rule that applies to a specific Abstract Syntax Tree (AST) element.
///
/// This is what authors of custom rules should implement.
/// Documentation for rules can be auto-generated by deriving [`Documented`](derive@Documented).
// Once an analysis crate exists there should be a second rule-kind applying to
// an analyzed state
pub trait AstRule: Documented + Send + Sync + 'static {
    /// The node that this rule applies to.
    /// Note: [DesignFileSyntax](vhdl_syntax::syntax::DesignFileSyntax)
    /// can be used to match on the full file.
    type Node: AstNode;

    const CODE: ErrorCode;

    const SEVERITY: Severity = Severity::Warning;

    const DEFAULT_ENABLED: bool = true;

    fn check(&self, node: &Valid<Self::Node>, ctx: &mut AstRuleCtx<'_>);
}

/// A type-erased and object-safe view of an [`AstRule`].
pub trait ErasedAstRule: Send + Sync {
    fn code(&self) -> ErrorCode;

    /// See [`Documented::DOCS`].
    fn docs(&self) -> &'static RuleDocs;

    /// Every node kind this rule wants to be called for.
    fn applies_to(&self) -> &'static [NodeKind];

    /// Run the rule against a node whose kind is one of [`Self::applies_to`].
    fn check_raw(&self, node: SyntaxNode, ctx: &mut AstRuleCtx<'_>);

    fn is_enabled_by_default(&self) -> bool;

    fn severity(&self) -> Severity;
}

impl<R: AstRule> ErasedAstRule for R {
    fn code(&self) -> ErrorCode {
        R::CODE
    }

    fn docs(&self) -> &'static RuleDocs {
        R::DOCS
    }

    fn applies_to(&self) -> &'static [NodeKind] {
        <R::Node as AstNode>::META.concrete_kinds()
    }

    fn check_raw(&self, node: SyntaxNode, ctx: &mut AstRuleCtx) {
        self.check(
            &Valid::new_unchecked(<R::Node as AstNode>::cast_unchecked(node)),
            ctx,
        )
    }

    fn is_enabled_by_default(&self) -> bool {
        R::DEFAULT_ENABLED
    }

    fn severity(&self) -> Severity {
        R::SEVERITY
    }
}

pub fn register_builtin_rules(registry: &mut RuleRegistry) {
    registry.register(NoParensAroundIf).unwrap();
    registry.register(ExplicitPortMode).unwrap();
}
